site_name: dayplot
site_url: https://example.com
repo_url: https://github.com/JosephBARBIERDARNAL/dayplot

theme:
  name: material
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Gallery: gallery.md
  - Contributing: contributing.md
  - Tuto:
    - tuto/basic-styling.md
    - tuto/negative-values.md
    - tuto/boxstyle.md
    - tuto/combine-charts.md
    - tuto/fetch-github-contribs.md
    - tuto/advanced.md

extra_css:
  - stylesheets/style.css

extra:
  analytics:
    provider: google
    property: G-JCXSYFN2WD

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg