[project]
name = "githubchart"
version = "0.1.0"
description = "day plotting"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
]

[project.optional-dependencies]
data = [
    "pandas>=2.2.3",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "mkdocs-material>=9.5.50",
    "pre-commit>=4.0.1",
    "pytest>=8.3.4",
]
